// inbound-call-claim — the Twilio-authoritative inbound ANSWER-CLAIM webhook (plan rev5 §4.4, R13).
//
// This function is NO LONGER a browser API. Ownership of an inbound call is written exclusively when
// Twilio itself reports the answered child leg via the per-agent signed statusCallback generated by
// twilio-voice-inbound (<Client statusCallbackEvent="answered completed" …>). The browser performs no
// ownership write; its accept event is UI state only. Requests without a valid Twilio signature —
// including every legacy JWT browser request from stale bundles — are rejected with ZERO writes.
//
// R19 delivery contract: CallStatus='in-progress' (answered) is the primary proof and
// CallStatus='completed' is the lost-answered recovery proof; canceled/busy/failed/no-answer losing
// legs never claim (2xx, no retries). Transient DB/RPC failures return 5xx so the callback URL's
// connection-override retry policy (#rc=3&rp=5xx,ct,rt — Twilio does not retry 5xx by default)
// redelivers; valid business rejections return 2xx. A delayed authentic callback may enrich an
// already-terminal row (ownership only) — the live-state precheck is deliberately absent.

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  checkAnsweredClientIdentity,
  classifyCallbackEvent,
  decideClaimResponseStatus,
  extractClientIdentity,
  isValidCallSid,
  parseClaimCallbackParams,
} from "./claim-callback.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-twilio-signature",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const jsonHeaders = { ...corsHeaders, "Content-Type": "application/json" };

function supabasePublicOrigin(): string {
  return (Deno.env.get("SUPABASE_URL") ?? "").trim().replace(/\/+$/, "");
}

function edgeFunctionAbsoluteUrl(req: Request, slug: string): string {
  const origin = supabasePublicOrigin();
  const search = new URL(req.url).search;
  return `${origin}/functions/v1/${slug}${search}`;
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary);
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function validateTwilioSignature(
  req: Request,
  authToken: string,
  params: Record<string, string>,
): Promise<boolean> {
  const signature = req.headers.get("x-twilio-signature");
  if (!signature) return false;

  // Twilio signs the full URL INCLUDING the server-issued call_row_id/agent_id query params (the
  // retry-override fragment is never transmitted), plus the sorted form body.
  const fullUrl = edgeFunctionAbsoluteUrl(req, "inbound-call-claim");

  const sortedKeys = Object.keys(params).sort();
  let signingString = fullUrl;
  for (const k of sortedKeys) signingString += k + params[k];

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(authToken),
    { name: "HMAC", hash: "SHA-1" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signingString));
  const expected = bytesToBase64(new Uint8Array(sig));
  return timingSafeEqual(expected, signature);
}

async function parseFormBody(req: Request): Promise<Record<string, string>> {
  const raw = await req.text();
  const params: Record<string, string> = {};
  const search = new URLSearchParams(raw);
  for (const [k, v] of search.entries()) params[k] = v;
  return params;
}

function respond(status: number, body: Record<string, unknown>): Response {
  return new Response(JSON.stringify(body), { status, headers: jsonHeaders });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return respond(405, { error: "Method not allowed" });
  }

  try {
    const authToken = Deno.env.get("TWILIO_AUTH_TOKEN");
    if (!authToken) {
      console.error("[inbound-call-claim] Missing TWILIO_AUTH_TOKEN");
      return respond(500, { error: "misconfigured" });
    }

    const params = await parseFormBody(req);

    // (1) Twilio signature is the ONLY accepted authority. Legacy browser requests (JSON + JWT) have
    // no valid signature and are rejected here with zero writes — the legacy claim contract is dead.
    const valid = await validateTwilioSignature(req, authToken, params);
    if (!valid) {
      console.warn("[inbound-call-claim] rejected", { reason: "bad_signature" });
      return respond(decideClaimResponseStatus({ kind: "bad_signature" }), { claimed: false, reason: "bad_signature" });
    }

    // (2) R19 event policy.
    const callStatus = params["CallStatus"] ?? "";
    const eventClass = classifyCallbackEvent(callStatus);
    if (eventClass !== "claim") {
      // Losing legs and non-answer events: 2xx ack, no write, no retries.
      return respond(decideClaimResponseStatus({ kind: "ignored" }), {
        claimed: false, ignored: true, callStatus, eventClass,
      });
    }

    // (3) Server-issued ids from the signed query (R13 — never from the browser) + strict SIDs (R16).
    const url = new URL(req.url);
    const ids = parseClaimCallbackParams(url);
    const childSid = (params["CallSid"] ?? "").trim();
    const parentSid = (params["ParentCallSid"] ?? "").trim();
    if (!ids || !isValidCallSid(childSid) || !isValidCallSid(parentSid)) {
      console.warn("[inbound-call-claim] rejected", {
        reason: "invalid_params", ids: !!ids,
        childValid: isValidCallSid(childSid), parentValid: isValidCallSid(parentSid),
      });
      return respond(decideClaimResponseStatus({ kind: "rejected" }), { claimed: false, reason: "invalid_params" });
    }

    const supabase: SupabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );

    // (4) Cross-checks (all database-authoritative; transient lookup failures ⇒ retryable 5xx).
    const { data: callRow, error: callErr } = await supabase
      .from("calls")
      .select("id, organization_id, direction, twilio_call_sid, routed_agent_ids")
      .eq("id", ids.callRowId)
      .maybeSingle();
    if (callErr) {
      console.error("[inbound-call-claim] transient calls lookup failure:", callErr.message);
      return respond(decideClaimResponseStatus({ kind: "transient" }), { claimed: false, reason: "transient" });
    }
    const row = callRow as {
      id: string; organization_id: string | null; direction: string | null;
      twilio_call_sid: string | null; routed_agent_ids: string[] | null;
    } | null;
    if (!row || row.direction !== "inbound" || row.twilio_call_sid !== parentSid) {
      console.warn("[inbound-call-claim] rejected", {
        reason: !row ? "row_not_found" : "parent_sid_mismatch",
        call_row_id: ids.callRowId, agent_id: ids.agentId, parentSid,
      });
      return respond(decideClaimResponseStatus({ kind: "rejected" }), { claimed: false, reason: "row_mismatch" });
    }

    const { data: profile, error: profErr } = await supabase
      .from("profiles")
      .select("id, organization_id, status, twilio_client_identity")
      .eq("id", ids.agentId)
      .maybeSingle();
    if (profErr) {
      console.error("[inbound-call-claim] transient profile lookup failure:", profErr.message);
      return respond(decideClaimResponseStatus({ kind: "transient" }), { claimed: false, reason: "transient" });
    }
    const prof = profile as {
      id: string; organization_id: string | null; status: string | null;
      twilio_client_identity: string | null;
    } | null;
    if (
      !prof ||
      prof.status !== "Active" ||
      !prof.organization_id ||
      prof.organization_id !== row.organization_id
    ) {
      console.warn("[inbound-call-claim] rejected", {
        reason: "agent_identity_mismatch", detail: "inactive_or_cross_org_profile",
        call_row_id: ids.callRowId, agent_id: ids.agentId,
      });
      return respond(decideClaimResponseStatus({ kind: "rejected" }), { claimed: false, reason: "agent_identity_mismatch" });
    }

    // C4 (rev 6): the R13 answered-identity cross-check FAILS CLOSED. The answered child leg's
    // Called/To client identity must be PRESENT and EXACTLY equal to the Active profile's nonempty
    // twilio_client_identity. Missing, empty, or mismatched identity is a 2xx business rejection
    // with zero RPC/write activity — a signed callback can never claim without proving which
    // client leg answered.
    const identityCheck = checkAnsweredClientIdentity({
      calledParam: params["Called"],
      toParam: params["To"],
      profileIdentity: prof.twilio_client_identity,
    });
    if (identityCheck !== "match") {
      console.warn("[inbound-call-claim] rejected", {
        reason: "agent_identity_mismatch", detail: identityCheck,
        call_row_id: ids.callRowId, agent_id: ids.agentId,
        answeredIdentity:
          extractClientIdentity(params["Called"]) || extractClientIdentity(params["To"]) || "(missing)",
      });
      return respond(decideClaimResponseStatus({ kind: "rejected" }), { claimed: false, reason: "agent_identity_mismatch" });
    }
    if (!Array.isArray(row.routed_agent_ids) || !row.routed_agent_ids.includes(ids.agentId)) {
      // R3 fail-closed: durably persisted routing membership is required.
      console.warn("[inbound-call-claim] rejected", {
        reason: "no_routed_agents_or_not_routed", call_row_id: ids.callRowId, agent_id: ids.agentId,
      });
      return respond(decideClaimResponseStatus({ kind: "rejected" }), { claimed: false, reason: "not_routed" });
    }

    // (5) The service-role-only CAS RPC (R1 core): first write claims; duplicates are read-only
    // idempotent successes (C1); terminal rows are enriched, never regressed (R19).
    const { data: claim, error: claimErr } = await supabase.rpc("claim_inbound_call", {
      p_user_id: ids.agentId,
      p_call_row_id: ids.callRowId,
      p_child_call_sid: childSid,
      p_parent_call_sid: parentSid,
    });
    if (claimErr) {
      console.error("[inbound-call-claim] transient claim rpc failure:", claimErr.message);
      return respond(decideClaimResponseStatus({ kind: "transient" }), { claimed: false, reason: "transient" });
    }
    const result = (claim ?? {}) as { claimed?: boolean; reason?: string; idempotent?: boolean; enriched_terminal?: boolean };
    if (result.claimed === true) {
      console.log("[inbound-call-claim] claimed", {
        call_row_id: ids.callRowId, agent_id: ids.agentId, callStatus,
        idempotent: result.idempotent === true, enriched_terminal: result.enriched_terminal === true,
      });
      return respond(decideClaimResponseStatus({ kind: "claimed" }), result as Record<string, unknown>);
    }
    // R3 actionable telemetry: every rejection carries its diagnosed reason code.
    console.warn("[inbound-call-claim] rejected", {
      reason: result.reason ?? "unknown", call_row_id: ids.callRowId, agent_id: ids.agentId, parentSid,
    });
    return respond(decideClaimResponseStatus({ kind: "rejected" }), result as Record<string, unknown>);
  } catch (err) {
    console.error("[inbound-call-claim] Fatal error:", err);
    return respond(decideClaimResponseStatus({ kind: "transient" }), { claimed: false, reason: "transient" });
  }
});
