-- Shared campaign configuration × Save Only/Next matrix. Disposable fixtures only.
\set ON_ERROR_STOP on

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(501),p_operation_id=>test_uuid(9531),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Team disposition 501 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Team suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(501),p_operation_id=>test_uuid(9532),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Team disposition 501 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Team suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(502),p_operation_id=>test_uuid(9532),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Team disposition 502 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Team suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(502),p_operation_id=>test_uuid(9533),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Team disposition 502 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Team suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(503),p_operation_id=>test_uuid(9533),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=false,'matrix Team disposition 503 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=1 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix non-DNC does not suppress another campaign');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(103),campaign_lead_id=test_uuid(303),contact_id=test_uuid(202) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team issued lock');
SELECT public.advance_campaign_lead(test_uuid(303),test_uuid(401),test_uuid(503),p_operation_id=>test_uuid(9534),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=false,'matrix Team disposition 503 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(303)),'matrix Team release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(303)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=1 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix non-DNC does not suppress another campaign');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(501),p_operation_id=>test_uuid(9541),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Open disposition 501 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Open suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(501),p_operation_id=>test_uuid(9542),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Open disposition 501 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Open suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(502),p_operation_id=>test_uuid(9542),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Open disposition 502 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Open suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(502),p_operation_id=>test_uuid(9543),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=true,'matrix Open disposition 502 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix Open suppresses Personal');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'matrix Team+Open phone suppression');
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(104))),'matrix DNC never reclaimed');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(503),p_operation_id=>test_uuid(9543),p_expected_version=>0,p_release_lock=>false);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=false,'matrix Open disposition 503 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=1 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release false');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=1 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix non-DNC does not suppress another campaign');
ROLLBACK;

BEGIN;
DELETE FROM public.dialer_lead_locks;
DELETE FROM public.calls WHERE id=test_uuid(402);
UPDATE public.calls SET campaign_id=test_uuid(104),campaign_lead_id=test_uuid(304),contact_id=test_uuid(201) WHERE id=test_uuid(401);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(304) FROM public.get_next_queue_lead(test_uuid(104))),'matrix Open issued lock');
SELECT public.advance_campaign_lead(test_uuid(304),test_uuid(401),test_uuid(503),p_operation_id=>test_uuid(9544),p_expected_version=>0,p_release_lock=>true);
SELECT test_assert((public.check_dialer_dnc('(555) 123-4567')->>'blocked')::boolean=false,'matrix Open disposition 503 DNC configuration');
RESET ROLE;
SELECT test_assert((SELECT count(*)=0 FROM public.dialer_lead_locks WHERE campaign_lead_id=test_uuid(304)),'matrix Open release true');
SELECT test_assert((SELECT call_attempts=1 FROM public.campaign_leads WHERE id=test_uuid(304)),'matrix one real attempt');
SELECT test_assert((SELECT duration=47 FROM public.calls WHERE id=test_uuid(401)),'matrix duration preserved');
SELECT test_assert((SELECT count(*)=5 FROM public.campaign_leads),'matrix all history retained');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=1 FROM public.get_personal_queue_leads(test_uuid(101))),'matrix non-DNC does not suppress another campaign');
ROLLBACK;

BEGIN;
UPDATE public.campaigns SET require_licensed_state_access=true WHERE id=test_uuid(103);
UPDATE public.campaign_leads SET state='Texas' WHERE id=test_uuid(303);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'unlicensed state excluded');
RESET ROLE;
INSERT INTO public.agent_state_licenses VALUES(test_uuid(11),test_uuid(1),'TX');
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'licensed state normalization accepted');
ROLLBACK;
BEGIN;
UPDATE public.campaign_leads SET callback_due_at=now()+interval '6 minutes',callback_agent_id=test_uuid(11) WHERE id=test_uuid(303);
SELECT test_actor(11); SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT count(*)=0 FROM public.get_next_queue_lead(test_uuid(103))),'callback outside manual five-minute window excluded');
RESET ROLE;
UPDATE public.campaign_leads SET callback_due_at=now()+interval '4 minutes' WHERE id=test_uuid(303);
SET LOCAL ROLE authenticated;
SELECT test_assert((SELECT id=test_uuid(303) FROM public.get_next_queue_lead(test_uuid(103))),'callback within manual window selectable');
ROLLBACK;
