SELECT test_actor(11);
INSERT INTO public.company_settings VALUES(test_id(1),'America/Los_Angeles');
SET ROLE authenticated;
SELECT test_reject($q$SELECT create_client_with_sale(test_id(10100),test_id(1),test_client_payload(),false)$q$,'22023');
INSERT INTO test_results VALUES('identity-contact',create_client_with_sale(test_id(10101),test_id(1),test_client_payload()-ARRAY['carrier','premium','sold_date'],false));
INSERT INTO test_results VALUES('identity-new',create_client_with_sale(test_id(10102),test_id(1),test_client_payload(),true));
INSERT INTO test_results VALUES('identity-first',update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Whole Life","carrier":"Test","premium":58.45,"sold_date":"2026-09-28"}'));
INSERT INTO test_results VALUES('identity-first-retry',update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Whole Life","carrier":"Test","premium":58.45,"sold_date":"2026-09-28"}'));
INSERT INTO test_results VALUES('identity-extra',record_client_policy(test_id(10103),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Term","carrier":"Test","premium":41.64,"sold_date":"2026-09-28"}'));
INSERT INTO test_results VALUES('identity-extra-retry',record_client_policy(test_id(10103),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Term","carrier":"Test","premium":41.64,"sold_date":"2026-09-28"}'));
INSERT INTO test_results VALUES('identity-unknown',record_client_policy(test_id(10104),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Term","carrier":"Test","premium":null,"sold_date":"2026-09-28"}'));
SELECT test_reject($q$SELECT record_client_policy(test_id(10103),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"policy_type":"Term","carrier":"Test","premium":80,"sold_date":"2026-09-28"}')$q$,'22023');
SELECT test_reject($q$SELECT update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),jsonb_build_object('organization_id',test_id(2)))$q$,'22023');
RESET ROLE;
SET CONSTRAINTS ALL IMMEDIATE;
SELECT test_assert((SELECT jsonb_array_length(data->'win_ids')=1 FROM test_results WHERE key='identity-first'),'first policy creates one event');
SELECT test_assert((SELECT data->'win_ids'='[]'::jsonb FROM test_results WHERE key='identity-first-retry'),'first policy retry/edit creates no second event');
SELECT test_assert((SELECT data->'win_ids' FROM test_results WHERE key='identity-extra')=(SELECT data->'win_ids' FROM test_results WHERE key='identity-extra-retry'),'additional policy retry returns same event');
SELECT test_assert((SELECT count(*)=3 AND sum(premium_amount)=100.09 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact')),'three distinct policies, known premium sum and no duplicates');
SELECT test_assert((SELECT premium_amount IS NULL AND premium_snapshot FROM wins WHERE policy_id=test_id(10104)),'unknown snapshot remains NULL');
SELECT test_assert((SELECT count(*)=3 FROM private.policy_identities WHERE client_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact')),'all policies registered');
SELECT test_reject($q$INSERT INTO clients(organization_id,first_name,last_name,carrier,sold_date) VALUES(test_id(1),'Bypass','Policy','Test','2026-09-28')$q$,'23514');
SELECT test_reject($q$INSERT INTO wins(organization_id,contact_id,agent_id) VALUES(test_id(1),test_id(999),test_id(11))$q$,'23514');
SELECT test_reject($q$DELETE FROM wins WHERE policy_id=test_id(10103)$q$,'23514');
SELECT test_reject($q$UPDATE wins SET premium_amount=1000 WHERE policy_id=test_id(10103)$q$,'23514');
SET CONSTRAINTS ALL DEFERRED;
SELECT test_actor(12);
SET ROLE authenticated;
SELECT test_reject($q$SELECT record_client_policy(test_id(10105),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),test_client_payload())$q$,'42501');
SELECT test_reject($q$SELECT update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"notes":"not mine"}')$q$,'42501');
RESET ROLE;
SELECT test_actor(11);
SET ROLE authenticated;
INSERT INTO test_results VALUES('identity-history',create_client_with_sale(test_id(10110),test_id(1),test_client_payload()||'{"sale_mode":"historical","sold_date":"2026-09-28"}',true));
INSERT INTO test_results VALUES('identity-legacy-edit',update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='manual'),'{"notes":"Unrelated edit"}'));
RESET ROLE;
SELECT test_assert((SELECT created_at='2026-09-28T07:00:00Z' AND celebrated AND event_time_source='sold_date_proxy' AND recorded_at>created_at FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-history')),'historical entry records disclosed agency-date proxy without celebration');
SELECT test_assert((SELECT data->'win_ids'='[]'::jsonb FROM test_results WHERE key='identity-legacy-edit'),'unrelated legacy edit adds no sale');
INSERT INTO leads(id,organization_id,user_id,assigned_agent_id,first_name,last_name) VALUES(test_id(10111),test_id(1),test_id(11),test_id(11),'Identity','Converted');
SET ROLE authenticated;
INSERT INTO test_results VALUES('identity-conversion',convert_lead_to_client_with_sales(test_id(10111),test_id(1),(SELECT data FROM test_results WHERE key='conversion-payload'),null));
RESET ROLE;
SELECT test_assert((SELECT count(*)=3 AND count(DISTINCT policy_id)=3 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-conversion')),'upgraded conversion persists one identity/event per primary/additional policy');
SELECT test_assert(NOT has_function_privilege('authenticated','private.ensure_policy_identity()','EXECUTE') AND NOT has_function_privilege('anon','public.record_client_policy(uuid,uuid,jsonb,boolean)','EXECUTE'),'new helper and endpoint grants are sealed');
SELECT test_assert(md5(pg_get_functiondef('public.convert_lead_to_client_atomic(uuid,jsonb)'::regprocedure))='641ba66c96ca4a76f80c9c85eb9caa42','original conversion body intact');
-- Explicit new intent cannot silently duplicate an already numbered carrier policy.
SELECT test_actor(11);
SET ROLE authenticated;
INSERT INTO test_results VALUES('numbered-policy',record_client_policy(test_id(10120),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),test_client_payload()||'{"policy_number":"AbC-123"}'));
SELECT test_reject($q$SELECT record_client_policy(test_id(10121),(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),test_client_payload()||'{"policy_number":" abc-123 ","carrier":" test carrier "}')$q$,'22023');
INSERT INTO test_results VALUES('reorder',update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),jsonb_build_object('custom_fields',jsonb_build_object('additional_policies',(SELECT jsonb_agg(x ORDER BY ord DESC) FROM test_results r,jsonb_array_elements(r.data->'client'->'custom_fields'->'additional_policies') WITH ORDINALITY a(x,ord) WHERE r.key='numbered-policy')))));
RESET ROLE;
SELECT test_assert((SELECT count(*)=4 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact')),'reorder preserves four existing sale identities');
SELECT test_actor(13);
SET ROLE authenticated;
INSERT INTO test_results VALUES('reassign',update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),jsonb_build_object('assigned_agent_id',test_id(12),'premium',777)));
RESET ROLE;
SELECT test_assert((SELECT bool_and(agent_id=test_id(11)) AND sum(premium_amount)=200.09 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact')),'reassignment and edit preserve original seller and premium');
-- Current-book removals never remove the original sale or permit identity reuse.
SET ROLE authenticated;
SELECT update_client_with_policy_sale((SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact'),'{"custom_fields":{"additional_policies":[]}}');
RESET ROLE;
SELECT test_assert((SELECT count(*)=4 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-contact')),'removing current-book policies retains sale history');
DELETE FROM clients WHERE id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-new');
SELECT test_assert((SELECT count(*)=1 FROM wins WHERE contact_id=(SELECT (data->>'client_id')::uuid FROM test_results WHERE key='identity-new')),'client deletion retains original sale');
SELECT test_reject($q$INSERT INTO clients(id,organization_id,first_name,last_name) SELECT (data->>'client_id')::uuid,test_id(1),'Reused','Identity' FROM test_results WHERE key='identity-new'$q$,'23514');
