// twilio-recording-status — R17 verified-persistence recording pipeline (plan rev5 §7).
//
// Contract: a valid recording_storage_path on the matched row is the ONLY success short-circuit
// (failure sentinels are recoverable states, not successes). The Twilio source recording is deleted
// ONLY after storage upload AND a verified exact-row DB metadata write both succeed. Every recoverable
// failure preserves the Twilio source, best-effort writes the guarded sentinel, and returns HTTP 5xx —
// the recordingStatusCallback URLs generated by twilio-voice-inbound carry the connection-override
// retry policy (#rc=3&rp=5xx,ct,rt) because Twilio's default policy does NOT retry 5xx. Unmatched
// callbacks never download, upload, or delete. Row updates are row-id + organization-scoped.

import { createClient, SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  classifyRecordingRow,
  decideRecordingResponseStatus,
  runRecordingPipeline,
  shouldWriteFailureSentinel,
} from "./idempotency.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-twilio-signature",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const twimlHeaders = { ...corsHeaders, "Content-Type": "text/xml" };

const EMPTY_TWIML = '<?xml version="1.0" encoding="UTF-8"?><Response></Response>';

function supabasePublicOrigin(): string {
  return (Deno.env.get("SUPABASE_URL") ?? "").trim().replace(/\/+$/, "");
}

function edgeFunctionAbsoluteUrl(req: Request, slug: string): string {
  const origin = supabasePublicOrigin();
  const search = new URL(req.url).search;
  return `${origin}/functions/v1/${slug}${search}`;
}

function bytesToBase64(bytes: Uint8Array): string {
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  return btoa(binary);
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function validateTwilioSignature(
  req: Request,
  authToken: string,
  params: Record<string, string>,
): Promise<boolean> {
  const signature = req.headers.get("x-twilio-signature");
  if (!signature) return false;

  const fullUrl = edgeFunctionAbsoluteUrl(req, "twilio-recording-status");

  const sortedKeys = Object.keys(params).sort();
  let signingString = fullUrl;
  for (const k of sortedKeys) signingString += k + params[k];

  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(authToken),
    { name: "HMAC", hash: "SHA-1" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(signingString));
  const expected = bytesToBase64(new Uint8Array(sig));
  return timingSafeEqual(expected, signature);
}

async function parseFormBody(req: Request): Promise<Record<string, string>> {
  const raw = await req.text();
  const params: Record<string, string> = {};
  for (const [k, v] of new URLSearchParams(raw).entries()) params[k] = v;
  return params;
}

function buildBasicAuth(accountSid: string, authToken: string): string {
  return "Basic " + btoa(`${accountSid}:${authToken}`);
}

function buildStoragePath(orgId: string, callSid: string): string {
  const now = new Date();
  const yyyy = now.getUTCFullYear();
  const mm = String(now.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(now.getUTCDate()).padStart(2, "0");
  return `${orgId}/${yyyy}${mm}${dd}/${callSid}.mp3`;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }
  if (req.method !== "POST") {
    return new Response(EMPTY_TWIML, { status: 405, headers: twimlHeaders });
  }

  try {
    const authToken = Deno.env.get("TWILIO_AUTH_TOKEN");
    const accountSid = Deno.env.get("TWILIO_ACCOUNT_SID");
    if (!authToken || !accountSid) {
      console.error("[twilio-recording-status] Missing TWILIO_AUTH_TOKEN or TWILIO_ACCOUNT_SID");
      return new Response(EMPTY_TWIML, { status: 500, headers: twimlHeaders });
    }

    const params = await parseFormBody(req);

    const valid = await validateTwilioSignature(req, authToken, params);
    if (!valid) {
      console.warn("[twilio-recording-status] Signature validation failed");
      return new Response(EMPTY_TWIML, { status: 403, headers: twimlHeaders });
    }

    const recordingSid = params["RecordingSid"] ?? "";
    const recordingUrl = params["RecordingUrl"] ?? "";
    const recordingStatus = params["RecordingStatus"] ?? "";
    const recordingDuration = params["RecordingDuration"] ?? "0";
    const callSid = params["CallSid"] ?? "";
    const callAccountSid = params["AccountSid"] ?? accountSid;

    console.log(
      `[twilio-recording-status] Received recording ${recordingSid} for call ${callSid} (status=${recordingStatus})`,
    );

    if (recordingStatus !== "completed") {
      console.log(`[twilio-recording-status] Skipping non-completed status: ${recordingStatus}`);
      return new Response(EMPTY_TWIML, {
        status: decideRecordingResponseStatus("ignored"), headers: twimlHeaders,
      });
    }

    const supabase: SupabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
    );

    // Row lookup — includes the R17 idempotency columns.
    let row: {
      id: string; organization_id: string | null;
      recording_storage_path: string | null; recording_url: string | null;
    } | null = null;
    if (callSid) {
      const { data, error } = await supabase
        .from("calls")
        .select("id, organization_id, recording_storage_path, recording_url")
        .eq("twilio_call_sid", callSid)
        .maybeSingle();
      if (error) {
        // transient lookup failure: retryable — source preserved, nothing written
        console.error(`[twilio-recording-status] calls lookup failed for CallSid=${callSid}:`, error.message);
        return new Response(EMPTY_TWIML, {
          status: decideRecordingResponseStatus("retryable_failure"), headers: twimlHeaders,
        });
      }
      row = (data as typeof row) ?? null;
    }

    const rowClass = classifyRecordingRow(row);

    if (rowClass === "unmatched") {
      // R17: never delete the provider recording, never create an unrecoverable orphan — the source
      // stays intact at Twilio for manual recovery.
      console.warn(
        `[twilio-recording-status] Unmatched CallSid=${callSid} (recording ${recordingSid}) — acking without download/upload/delete; Twilio source preserved`,
      );
      return new Response(EMPTY_TWIML, {
        status: decideRecordingResponseStatus("unmatched"), headers: twimlHeaders,
      });
    }

    if (rowClass === "skip_already_stored") {
      // The ONLY success short-circuit: a valid stored path. A duplicate callback (whose re-download
      // would 404 after the post-success delete) can no longer clobber success with a sentinel.
      console.log(
        `[twilio-recording-status] Recording already stored for CallSid=${callSid} (${row!.recording_storage_path}) — duplicate ack`,
      );
      return new Response(EMPTY_TWIML, {
        status: decideRecordingResponseStatus("skip_already_stored"), headers: twimlHeaders,
      });
    }

    const orgId = row!.organization_id ?? "unmatched";
    const storagePath = buildStoragePath(orgId, callSid || recordingSid);
    const rowId = row!.id;

    const result = await runRecordingPipeline({
      download: async () => {
        const dlRes = await fetch(`${recordingUrl}.mp3`, {
          headers: { Authorization: buildBasicAuth(accountSid, authToken) },
        });
        if (!dlRes.ok) throw new Error(`download HTTP ${dlRes.status} ${dlRes.statusText}`);
        const bytes = new Uint8Array(await dlRes.arrayBuffer());
        console.log(`[twilio-recording-status] Downloaded ${bytes.byteLength} bytes from Twilio`);
        return bytes;
      },
      upload: async (bytes) => {
        const { error: uploadError } = await supabase.storage
          .from("call-recordings")
          .upload(storagePath, bytes, { contentType: "audio/mpeg", upsert: true });
        if (uploadError) throw new Error(`upload: ${uploadError.message}`);
        console.log(`[twilio-recording-status] Uploaded to storage: ${storagePath}`);
      },
      persistMetadata: async () => {
        // R17: verified exact-row success — row-id + org-scoped, and zero rows is a FAILURE.
        const duration = parseInt(recordingDuration, 10);
        const { data: updated, error } = await supabase
          .from("calls")
          .update({
            recording_storage_path: storagePath,
            recording_duration: Number.isNaN(duration) ? null : duration,
            recording_url: `storage:${storagePath}`,
            updated_at: new Date().toISOString(),
          })
          .eq("id", rowId)
          .eq("organization_id", row!.organization_id)
          .select("id");
        if (error) throw new Error(`metadata persist: ${error.message}`);
        if (!updated || updated.length !== 1) throw new Error("metadata persist: exact-row update did not land");
        console.log(`[twilio-recording-status] Verified metadata persist for calls row ${rowId}`);
      },
      deleteSource: async () => {
        // Delete ONLY after storage upload + verified DB persistence (delete-only-after-commit).
        const deleteUrl = `https://api.twilio.com/2010-04-01/Accounts/${callAccountSid}/Recordings/${recordingSid}`;
        const delRes = await fetch(deleteUrl, {
          method: "DELETE",
          headers: { Authorization: buildBasicAuth(accountSid, authToken) },
        });
        if (!delRes.ok && delRes.status !== 404) {
          throw new Error(`delete HTTP ${delRes.status} ${delRes.statusText}`);
        }
        console.log(`[twilio-recording-status] Deleted recording ${recordingSid} from Twilio`);
      },
      writeFailureSentinel: async (stage) => {
        // Guarded: a sentinel may never overwrite a successful storage path (double-checked in SQL
        // via the .is() predicate — first-writer-wins).
        if (!shouldWriteFailureSentinel(row)) return;
        const sentinel = stage === "upload" ? "__recording_upload_failed__" : "__recording_failed__";
        const { error } = await supabase
          .from("calls")
          .update({ recording_url: sentinel, updated_at: new Date().toISOString() })
          .eq("id", rowId)
          .eq("organization_id", row!.organization_id)
          .is("recording_storage_path", null);
        if (error) {
          console.warn(`[twilio-recording-status] sentinel write failed (${stage}):`, error.message);
        }
      },
    });

    if (result.outcome === "retryable_failure") {
      console.error("[twilio-recording-status] RECORDING PIPELINE FAILED (retryable)", {
        recordingSid, callSid, rowId, stage: result.stage,
      });
    }
    return new Response(EMPTY_TWIML, {
      status: decideRecordingResponseStatus(result.outcome), headers: twimlHeaders,
    });
  } catch (err) {
    // Unknown failure: retryable — the Twilio source has not been deleted before verified persistence.
    console.error("[twilio-recording-status] Fatal error (retryable):", err);
    return new Response(EMPTY_TWIML, {
      status: decideRecordingResponseStatus("retryable_failure"), headers: twimlHeaders,
    });
  }
});
