"""Actual built-app browser checks; synthetic inputs, no live carrier or CRM calls."""
from pathlib import Path
import json, os, shutil
from playwright.sync_api import sync_playwright, expect
ROOT=Path(__file__).resolve().parents[2]
BASE=os.environ.get('UNDERWRITING_URL','http://127.0.0.1:4173')
OUT=ROOT/'.underwriting-check'; OUT.mkdir(exist_ok=True)
SHOTS=OUT/'screenshots'; SHOTS.mkdir(exist_ok=True)
checks=[]
def record(name): checks.append(name)
def load(browser,width=390):
    context=browser.new_context(viewport={'width':width,'height':900},device_scale_factor=1)
    page=context.new_page(); errors=[];requests=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    page.on('request',lambda r:requests.append(r.url))
    page.route('https://fonts.googleapis.com/**',lambda route:route.abort())
    page.route('https://fonts.gstatic.com/**',lambda route:route.abort())
    page.goto(BASE+'/underwriting',wait_until='networkidle')
    expect(page.locator('#age')).to_be_visible()
    assert not any('/App-' in u or 'supabase.co' in u or 'twilio.com' in u for u in requests),requests
    requests.clear()
    return context,page,errors,requests
def fill_basics(page,nicotine='never',age='65',state='TX'):
    page.locator('#age').fill(age);page.locator('#state').select_option(state)
    page.locator('#height').select_option('70');page.locator('#weight').fill('200')
    page.locator('#face').fill('20000');page.locator('#nicotine').select_option(nicotine)
    page.get_by_role('button',name='Continue',exact=True).click()
def no_history(page):
    page.locator('#conditionsStatus').select_option('none');page.locator('#medicationsStatus').select_option('none')
    page.get_by_role('button',name='Continue',exact=True).click()
def answer(page,name,value): page.locator(f'input[name="{name}"][value="{value}"]').check()
def safety_no(page):
    for name in ['oxygen12','adl12','hospice12','mobility12','pending']:answer(page,name,'no')
def reviewed(page):
    page.get_by_text('Carrier / state verification — optional, improves the review',exact=True).click()
    for name,value in [('amState','yes'),('moState','yes'),('moReviewed','yes'),('moPart1','no'),('moPart2','no')]:answer(page,name,value)
    page.locator('#moForm').fill('Synthetic state form / revision / TX')
def no_overflow(page):
    assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'),page.evaluate('({w:innerWidth,s:document.documentElement.scrollWidth})')
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
    browser=p.chromium.launch(**({'executable_path':executable} if executable else {}),args=['--no-sandbox'] if hasattr(os,'geteuid') and os.geteuid()==0 else [])
    for route in ['/underwriting','/underwritin','/underwriting/']:
        ctx=browser.new_context();page=ctx.new_page()
        page.route('https://fonts.googleapis.com/**',lambda r:r.abort());page.route('https://fonts.gstatic.com/**',lambda r:r.abort())
        page.goto(BASE+route,wait_until='networkidle');expect(page.locator('#age')).to_be_visible();ctx.close()
        record('Direct entry '+route)
    ctx,page,errors,requests=load(browser)
    expect(page.locator('#age')).to_have_value('')
    page.get_by_role('button',name='Continue',exact=True).click()
    expect(page.get_by_role('alert')).to_contain_text('Enter a whole-number age')
    expect(page.locator('#age')).to_be_focused();record('Empty submit shows validation and focuses first error')
    fill_basics(page);no_history(page)
    assert page.locator('input[type=radio]:checked').count()==0;record('No default negative health answers')
    page.get_by_role('button',name='Review carriers',exact=True).click()
    expect(page.locator('[data-carrier="americo"]')).to_contain_text('Needs review')
    expect(page.locator('[data-carrier="transamerica"]')).to_contain_text('Needs review');record('Unknown Transamerica facts remain review under the verified source')
    assert len(page.locator('article').all())==3;record('All three carriers render without fabricated quotes')
    page.get_by_role('button',name='← Back',exact=True).click();safety_no(page);reviewed(page)
    page.get_by_role('button',name='Review carriers',exact=True).click()
    expect(page.locator('[data-carrier="mutual"]')).to_contain_text('Level candidate')
    assert 'Select 1 eligible' not in page.locator('[data-carrier="americo"]').inner_text();record('Application-based candidate and Americo uncertainty stay distinct')
    page.locator('#commission-panel summary').click()
    page.get_by_role('button',name='Apply session reference',exact=True).click()
    expect(page.locator('#commission-panel')).to_contain_text('Complete the schedule name');record('Incomplete commission schedule rejected')
    page.locator('#schedule-reference').fill('Synthetic test reference');page.locator('#schedule-contract').fill('Synthetic contract')
    page.locator('#schedule-from').fill('2020-01-01');page.locator('#schedule-to').fill('2099-12-31')
    page.locator('#rate-mo-level').fill('120');page.locator('#schedule-ack').check()
    page.get_by_role('button',name='Apply session reference',exact=True).click()
    expect(page.locator('#commission-panel')).to_contain_text('No badge yet')
    assert page.get_by_text('Highest supplied rate · comparable candidates',exact=True).count()==0;record('One candidate cannot receive a highest-paying badge')
    page.get_by_role('button',name='Client basics',exact=False).click();page.locator('#age').fill('86')
    page.get_by_role('button',name='Continue',exact=True).click();page.get_by_role('button',name='Continue',exact=True).click()
    # Changing base facts invalidates the application affirmation as well as prior results.
    page.get_by_text('Carrier / state verification — optional, improves the review',exact=True).click()
    assert not page.locator('input[name=moReviewed][value=yes]').is_checked();record('Clinical edits invalidate state-application affirmation')
    page.get_by_role('button',name='Review carriers',exact=True).click()
    expect(page.locator('[data-carrier="mutual"]')).to_contain_text('Outside checked criteria')
    expect(page.locator('[data-carrier="americo"]')).to_contain_text('Outside checked criteria');record('Age edit recomputes results, not stale candidate')
    page.get_by_role('button',name='Clear case & session reference',exact=True).click()
    expect(page.locator('#age')).to_have_value('');assert page.locator('article').count()==0;record('Clear case removes inputs, results and reference')
    assert not errors,errors;assert not requests,requests;record('Full flow has zero runtime errors and zero network requests')
    page.screenshot(path=str(SHOTS/'mobile.png'),full_page=True)
    page.locator('#age').fill('65');page.evaluate("window.dispatchEvent(new Event('pagehide'))");assert page.locator('#age').count()==0
    page.evaluate("window.dispatchEvent(new Event('pageshow'))");expect(page.locator('#age')).to_have_value('')
    record('Back-forward-cache lifecycle clears the case before restoring a blank session');ctx.close()
    for width in [320,375,390,768,1440]:
        ctx,page,errors,requests=load(browser,width);no_overflow(page)
        fill_basics(page,'current');page.locator('#conditionsStatus').select_option('listed')
        page.get_by_role('button',name='COPD / emphysema / chronic bronchitis',exact=True).click()
        page.locator('#medicationsStatus').select_option('listed')
        page.locator('input[id^="med-rx"]').fill('Spiriva');page.locator('input[id^="ind-rx"]').fill('COPD')
        page.locator('select[id^="status-rx"]').select_option('current');no_overflow(page)
        page.get_by_role('button',name='Continue',exact=True).click();safety_no(page);answer(page,'respQuestion','yes');no_overflow(page)
        page.get_by_role('button',name='Review carriers',exact=True).click()
        expect(page.locator('[data-carrier="americo"]')).to_contain_text('No better than Select 2 Nicotine')
        expect(page.locator('[data-carrier="mutual"]')).to_contain_text('Graded consideration only');no_overflow(page)
        assert not errors,errors;assert not requests,requests
        if width==390:page.screenshot(path=str(SHOTS/'results-mobile.png'),full_page=True)
        if width==1440:page.screenshot(path=str(SHOTS/'results-desktop.png'),full_page=True)
        record(f'{width}px: four-stage COPD/Rx flow, exact tier ceiling, no overflow, no network/errors');ctx.close()
    ctx,page,errors,requests=load(browser)
    fill_basics(page);page.locator('#conditionsStatus').select_option('listed')
    page.get_by_role('button',name='COPD / emphysema / chronic bronchitis',exact=True).click()
    page.locator('#medicationsStatus').select_option('none');page.get_by_role('button',name='Continue',exact=True).click()
    answer(page,'respQuestion','yes');page.get_by_role('button',name='← Back',exact=True).click()
    page.get_by_role('button',name='COPD / emphysema / chronic bronchitis',exact=True).click()
    page.get_by_role('button',name='Another diagnosis',exact=True).click();page.locator('#otherCondition').fill('Unknown')
    page.get_by_role('button',name='Continue',exact=True).click()
    assert page.locator('input[name=respQuestion]').count()==0;record('Removing diagnosis removes its conditional question')
    page.get_by_role('button',name='← Back',exact=True).click()
    page.locator('#medicationsStatus').select_option('listed')
    payload='<img src=x onerror="window.pwned=true">'
    page.locator('input[id^="med-rx"]').fill(payload);page.locator('input[id^="ind-rx"]').fill('Unknown')
    page.locator('select[id^="status-rx"]').select_option('current')
    page.get_by_role('button',name='Continue',exact=True).click();page.get_by_role('button',name='Review carriers',exact=True).click()
    assert page.locator('img').count()==0;assert not page.evaluate('Boolean(window.pwned)');no_overflow(page)
    assert not errors,errors;assert not requests,requests;record('Untrusted medication text is literal text, not HTML; no external request')
    ctx.close()
    ctx,page,errors,requests=load(browser)
    fill_basics(page);no_history(page);safety_no(page);reviewed(page)
    page.get_by_text('Transamerica — source-specific follow-ups',exact=True).click()
    for name,value in [('taTobacco12','no'),('taCurrentSupport','no'),('taHospital','no'),('taPending','no'),('taLegal','no'),('taLifestyle','no'),('taEligibility','yes')]:answer(page,name,value)
    page.locator('#taForm').fill('Synthetic complete Transamerica application / TX')
    answer(page,'taReviewed','yes');page.get_by_role('button',name='Review carriers',exact=True).click()
    expect(page.locator('[data-carrier="transamerica"]')).to_contain_text('Premier candidate')
    record('Verified Transamerica application path produces a provisional candidate, not a source hold')
    page.locator('#commission-panel summary').click()
    page.locator('#schedule-reference').fill('Synthetic comparison');page.locator('#schedule-contract').fill('Synthetic contract')
    page.locator('#schedule-from').fill('2020-01-01');page.locator('#schedule-to').fill('2099-12-31')
    page.locator('#rate-mo-level').fill('90');page.locator('#rate-ta-premier').fill('120');page.locator('#schedule-ack').check()
    page.get_by_role('button',name='Apply session reference',exact=True).click()
    expect(page.locator('article').first).to_have_attribute('data-carrier','transamerica')
    expect(page.locator('[data-carrier="transamerica"]')).to_contain_text('Highest supplied rate')
    record('Complete comparable supplied rates sort peers and show the supported highest-rate badge')
    page.get_by_role('button',name='← Back',exact=True).click()
    page.get_by_text('Transamerica — source-specific follow-ups',exact=True).click()
    answer(page,'taHospital','yes')
    assert not page.locator('input[name=taReviewed][value=yes]').is_checked()
    page.get_by_role('button',name='Review carriers',exact=True).click()
    expect(page.locator('[data-carrier="transamerica"]')).to_contain_text('Outside checked criteria')
    assert page.get_by_text('Highest supplied rate · comparable candidates',exact=True).count()==0
    assert not errors,errors;assert not requests,requests
    record('Changing Transamerica clinical facts clears confirmation, classification and commission badge')
    ctx.close();browser.close()
(OUT/'browser-tests.json').write_text(json.dumps({'passed':len(checks),'failed':0,'environment':'Chromium; real repository Vite build served on localhost; not physical iOS or production validation','checks':checks},indent=2))
print(json.dumps({'passed':len(checks),'failed':0,'checks':checks},indent=2))
