const { test } = require('node:test');
const assert = require('node:assert/strict');
const base = '../../.underwriting-check/compiled/underwriting/chat/';
const { extractNote } = require(base + 'parse.js');
const { freshNotes, applyExtraction, confirmMedication, removeFact } = require(base + 'session.js');
const { nextQuestions, answerQuestion, contextualReply } = require(base + 'questions.js');
const { basicsSchema, basicsErrors, caseWithBasics, noteSchema } = require(base + 'basics.js');
const { quickCards } = require(base + 'evaluate.js');
const { suggestMedication } = require(base + 'medications.js');
const basics = {age:'65',state:'TX',height:'66',weight:'170',smoking:'nonsmoker',quitMonths:''};
const fresh = () => ({...freshNotes(),case:caseWithBasics(basics)});
const note = (text, state=fresh()) => applyExtraction(state, extractNote(text,state),text);
const answer = (state,id,value) => { const q=nextQuestions(state).find(q=>q.id===id);assert.ok(q,id);return answerQuestion(state,q,value); };
const greenCase = () => {let s=note('COPD');s=answer(s,'oxygen','no');s=answer(s,'care','no');s=answer(s,'recent','no');return answer(s,'complete','no');};
const ta = s => quickCards(basics,s).find(c=>c.carrier==='transamerica');
const am = s => quickCards(basics,s).find(c=>c.carrier==='americo');

test('quick basics do not require coverage, name, sex or a client record',()=>{
 assert.equal(basicsSchema.safeParse(basics).success,true);assert.equal(caseWithBasics(basics).face,'');
 assert.equal(basicsSchema.safeParse({...basics,name:'not permitted'}).success,false);
 assert.ok(Object.keys(basicsErrors({...basics,age:''})).includes('age'));
});
for(const [field,value] of [['age','65.2'],['age','1e2'],['age','101'],['state','ZZ'],['height','66.5'],['weight','Infinity'],['weight','-1'],['smoking','']])test(`quick basics reject ${field}=${value}`,()=>assert.equal(basicsSchema.safeParse({...basics,[field]:value}).success,false));
test('former nicotine requires actual months, other nicotine does not imply tobacco',()=>{
 assert.equal(basicsSchema.safeParse({...basics,smoking:'former'}).success,false);
 assert.equal(caseWithBasics({...basics,smoking:'other'}).answers.taTobacco12,'');
 assert.equal(caseWithBasics(basics).nicotineMonths,'24');
});
test('the exact requested example extracts three diagnoses without inventing a last-treatment date',()=>{
 const s=note('type 2 diabetes copd had cancer 7 years ago');
 assert.deepEqual(new Set(s.case.conditions),new Set(['diabetes','copd','cancer']));
 assert.equal(s.case.details.cancerHistoryMonths,'84');assert.equal(s.case.details.taCancerMonths,undefined);
 assert.equal(s.case.answers.taInsulin12,undefined);assert.deepEqual(s.unresolved,[]);assert.equal(nextQuestions(s).length,2);
});
for(const [text,ids] of [['type2 diabetes',['diabetes']],['T2DM',['diabetes']],['COPD and CHF',['copd','chf']],['AFib',['afib']],['had a stent',['heart_surgery']],['had a stroke',['stroke']],['cirrhosis',['liver']],['multiple sclerosis',['ms']],['Parkinson’s',['parkinson']]])test(`diagnosis phrase ${text}`,()=>assert.deepEqual(note(text).case.conditions,ids));
for(const text of ['mother had cancer','her father has COPD','family history of diabetes'])test(`family history is not applicant history: ${text}`,()=>assert.deepEqual(note(text).case.conditions,[]));
test('family history and applicant history can coexist in separate clauses',()=>assert.deepEqual(note('mother had cancer, client has COPD').case.conditions,['copd']));
test('negation list does not add conditions',()=>assert.deepEqual(note('no diabetes or copd').case.conditions,[]));
test('but ends negation scope',()=>assert.deepEqual(note('no diabetes but has copd').case.conditions,['copd']));
for(const text of ['possible COPD','might have COPD','not sure about COPD'])test(`uncertain diagnosis is not confirmed: ${text}`,()=>{const s=note(text);assert.deepEqual(s.case.conditions,[]);assert.equal(s.facts[0].value,'unknown');assert.ok(quickCards(basics,s).every(c=>c.color!=='green'));});
test('negative complication wording does not erase diabetes',()=>{
 const s=note('no diabetes complications',note('diabetes'));assert.deepEqual(s.case.conditions,['diabetes']);assert.equal(s.case.answers.diabetesComplication,'no');
});
test('no recurrence does not erase cancer',()=>assert.deepEqual(note('no cancer recurrence',note('cancer')).case.conditions,['cancer']));
test('neuropathy is not automatically attributed to diabetes',()=>assert.equal(note('neuropathy',note('diabetes')).case.answers.taDiabetesComplication,'unknown'));
test('explicit diabetic neuropathy is linked',()=>assert.equal(note('diabetic neuropathy',note('diabetes')).case.answers.taDiabetesComplication,'yes'));
test('history date is not treatment completion',()=>assert.equal(note('breast cancer 7 years ago').case.answers.taCancerComplete,undefined));
test('explicit treatment end has a valid date anchor',()=>{const s=note('breast cancer, treatment ended 7 years ago');assert.equal(s.case.details.taCancerMonths,'84');assert.equal(s.case.answers.taCancerComplete,'yes');});
test('stopped oxygen years ago is not current oxygen',()=>assert.equal(note('stopped oxygen 3 years ago').case.answers.oxygen12,'no'));
test('no oxygen now does not clear the 12-month period',()=>assert.equal(note('not on oxygen now').case.answers.oxygen12,undefined));
test('current supplemental oxygen triggers Americo published exclusion',()=>assert.equal(am(note('on oxygen')).color,'red'));
test('historical oxygen mention does not fabricate current use',()=>assert.notEqual(am(note('was on oxygen 7 years ago')).color,'red'));
test('current insulin absence does not clear past-year insulin',()=>{const s=note('no insulin',note('diabetes'));assert.equal(s.case.details.insulinCurrent,'no');assert.equal(s.case.answers.taInsulin12,undefined);assert.equal(s.case.medications.length,0);});
test('medication does not create a diagnosis',()=>{const s=note('takes metformin');assert.equal(s.case.conditions.length,0);assert.equal(s.case.medications[0].name,'Metformin');});
for(const [typed,wanted] of [['metfornin','Metformin'],['metphormin','Metformin'],['lisinipril','Lisinopril'],['gabapenten','Gabapentin'],['elequis','Eliquis']])test(`medication suggestion ${typed}`,()=>assert.ok(suggestMedication(typed).includes(wanted)));
test('misspelled medication stays uncommitted until agent confirmation',()=>{
 let s=note('takes metfornin');assert.equal(s.case.medications.length,0);assert.equal(s.suggestions.length,1);
 s=confirmMedication(s,'metfornin','Metformin');assert.equal(s.case.medications[0].name,'Metformin');assert.equal(s.case.conditions.length,0);assert.equal(s.suggestions.length,0);
});
test('wrong or invented confirmation rejected',()=>{const s=note('takes metfornin');assert.equal(confirmMedication(s,'metfornin','Aricept'),s);});
test('stopped medication is not a current exclusion',()=>{const s=note('stopped Aricept');assert.equal(s.case.medications[0].status,'stopped');assert.notEqual(quickCards(basics,s).find(c=>c.carrier==='mutual').color,'red');});
test('medication uncertainty not current use',()=>assert.equal(note('maybe taking Aricept').case.medications[0].status,'unknown'));
test('nearby exact look-alike medication names are not substituted',()=>{assert.deepEqual(suggestMedication('hydralazine'),['Hydralazine']);assert.deepEqual(suggestMedication('hydroxyzine'),['Hydroxyzine']);});
test('unknown medication name stays visible for review',()=>assert.ok(note('takes blorptin').unresolved.includes('blorptin')));
test('unknown diagnosis is not dropped beside a known one',()=>{const s=note('COPD and sarcoidosis');assert.ok(s.unresolved.includes('sarcoidosis'));assert.equal(ta(s).color,'yellow');});
test('informal negative cannot silently erase prior positive',()=>{const s=note('no copd',note('COPD'));assert.equal(s.facts.find(f=>f.key==='copd').value,'unknown');assert.equal(ta(s).color,'yellow');});
test('explicit correction replaces a wrong diagnosis',()=>{const s=note('actually no COPD',note('COPD'));assert.equal(s.case.conditions.length,0);assert.equal(s.facts.find(f=>f.key==='copd').value,'no');});
test('new adverse information invalidates a prior green screen',()=>{const s=greenCase();assert.equal(ta(s).color,'green');const next=note('on oxygen',s);assert.equal(am(next).color,'red');assert.notEqual(ta(next).color,'green');});
test('green quick screen never fabricates an application confirmation',()=>{const s=greenCase();const card=ta(s);assert.equal(card.color,'green');assert.equal(s.case.answers.taReviewed,undefined);assert.equal(s.case.answers.moReviewed,undefined);assert.equal(card.native.status,'review');assert.equal(card.native.tierKind,'ceiling');});
test('no false quote-range declines when amount is intentionally omitted',()=>assert.ok(quickCards(basics,note('COPD')).every(c=>!c.evidence.some(e=>/-FACE/.test(e.rule)))));
test('two conditions cannot be green by ignoring combination uncertainty',()=>assert.equal(ta(note('CHF',greenCase())).color,'yellow'));
test('unsupported user language prevents green',()=>assert.equal(ta(note('also pulmonary fibrosis',greenCase())).color,'yellow'));
test('pending spelling correction prevents green',()=>assert.equal(ta(note('takes metfornin',greenCase())).color,'yellow'));
test('source-incomplete Americo and Mutual do not become falsely green',()=>{const cards=quickCards(basics,greenCase());assert.equal(cards.find(c=>c.carrier==='americo').color,'yellow');assert.equal(cards.find(c=>c.carrier==='mutual').color,'yellow');});
test('source exclusions remain red despite unknown additional facts',()=>assert.equal(am(note('Parkinson’s and something unclear')).color,'red'));
test('unknown answer does not loop or turn into No',()=>{let s=note('COPD');s=answer(s,'oxygen','unknown');assert.equal(s.case.answers.oxygen12,'unknown');assert.ok(!nextQuestions(s).some(q=>q.id==='oxygen'));});
test('compound care Yes is not five inferred positive answers',()=>{let s=note('COPD');s=answer(s,'oxygen','no');s=answer(s,'care','yes');assert.equal(s.case.answers.adl12,'unknown');assert.equal(s.case.answers.hospice12,'unknown');assert.equal(am(s).color,'yellow');});
test('unqualified Yes with two questions is ambiguous',()=>{const s=note('COPD');assert.equal(contextualReply(s,'yes',nextQuestions(s)),null);});
test('bare duration anchors to a unique currently asked treatment question',()=>{let s=note('breast cancer');s=answer(s,'oxygen','no');const next=contextualReply(s,'7 years ago',nextQuestions(s));assert.equal(next.case.details.taCancerMonths,'84');});
test('remove diagnosis clears its dependent facts',()=>{const s=note('breast cancer, treatment ended 7 years ago');const next=removeFact(s,'condition:cancer');assert.equal(next.case.details.taCancerMonths,undefined);});
test('remove medication clears the evaluator row',()=>{const s=note('takes Aricept');const next=removeFact(s,'medication:aricept');assert.equal(next.case.medications.length,0);assert.notEqual(quickCards(basics,next).find(c=>c.carrier==='mutual').color,'red');});
test('always at most two questions',()=>{for(const text of ['COPD','type 2 diabetes copd cancer','heart attack stent cancer diabetes','healthy no meds'])assert.ok(nextQuestions(note(text)).length<=2);});
test('note validator rejects empty and oversized input',()=>{assert.equal(noteSchema.safeParse(' ').success,false);assert.equal(noteSchema.safeParse('x'.repeat(3001)).success,false);});

test('no other medications does not also assert a complete condition history',()=>{const s=note('no other medications');assert.equal(s.case.medicationsStatus,'none');assert.equal(s.case.conditionsStatus,'unknown');assert.ok(!s.facts.some(f=>f.key==='complete'));});
test('no other conditions does not assert complete medication history',()=>{const s=note('no other conditions');assert.equal(s.case.medicationsStatus,'unknown');assert.ok(!s.facts.some(f=>f.key==='complete'));});
test('not healthy is not a negative condition screen',()=>assert.equal(note('not healthy').case.conditionsStatus,'unknown'));
test('generic arrhythmia is not relabeled as atrial fibrillation',()=>{const s=note('arrhythmia');assert.ok(!s.case.conditions.includes('afib'));assert.ok(s.unresolved.length);});
test('CPAP equipment does not silently diagnose sleep apnea',()=>{const s=note('uses CPAP');assert.ok(!s.case.conditions.includes('sleep_apnea'));assert.ok(s.unresolved.length);});
test('never attached to another treatment does not clear oxygen use',()=>assert.notEqual(note('never insulin and on oxygen').case.answers.oxygen12,'no'));
test('correcting an unknown cancer type removes the stale unknown flag',()=>{let s=note('cancer');s=answer(s,'cancer-type','unknown');s=note('breast cancer',s);assert.equal(s.case.details.taCancerType,'breast');assert.ok(!s.facts.some(f=>f.key==='unknown:cancer-type'));});
