import { TrainingResource } from "@/types/training";

export const MOCK_RESOURCES: TrainingResource[] = [
  {
    id: "1",
    title: "Mastering the Opening Call",
    description: "Learn the secrets to hooking a prospect in the first 30 seconds of a life insurance call.",
    type: "video",
    category: "Sales Training",
    thumbnailUrl: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&q=80&w=400",
    contentUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "8:45",
    isCompleted: true,
    createdAt: "2024-03-20",
  },
  {
    id: "2",
    title: "The Final Expense Script",
    description: "Our high-converting script for Final Expense leads, including common objection handlers.",
    type: "script",
    category: "Scripts",
    content: "# Final Expense Sales Script\n\n## Introduction\nHello, is this [Prospect Name]? Hi [Prospect Name], this is [Your Name] with AgentFlow. I'm calling about the information you requested regarding the new state-regulated final expense programs...\n\n## Objection: I'm not interested\nI understand, [Prospect Name]. Most people I speak with weren't looking for insurance today either, but they were interested in making sure their family wasn't burdened with $15,000 in funeral costs. Does that make sense?",
    isCompleted: false,
    createdAt: "2024-03-21",
  },
  {
    id: "3",
    title: "Term Life Product Guide 2024",
    description: "A comprehensive guide to all Term Life products offered by our primary carriers.",
    type: "document",
    category: "Product Knowledge",
    thumbnailUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=400",
    contentUrl: "#",
    fileSize: "1.2 MB",
    isCompleted: false,
    createdAt: "2024-03-22",
  },
  {
    id: "4",
    title: "Overcoming the 'Talk to My Spouse' Objection",
    description: "Advanced techniques for handling the most common objection in life insurance sales.",
    type: "video",
    category: "Sales Training",
    thumbnailUrl: "https://images.unsplash.com/photo-1521791136064-7986c2959210?auto=format&fit=crop&q=80&w=400",
    contentUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    duration: "12:15",
    isCompleted: false,
    createdAt: "2024-03-23",
  },
  {
    id: "5",
    title: "Compliance Checklist",
    description: "Essential checklist for staying compliant during phone solicitations.",
    type: "document",
    category: "Compliance",
    thumbnailUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=400",
    contentUrl: "#",
    fileSize: "450 KB",
    isCompleted: true,
    createdAt: "2024-03-24",
  },
];

export const TRAINING_CATEGORIES = [
  "All",
  "Sales Training",
  "Scripts",
  "Product Knowledge",
  "Compliance",
];
