export type LegalSection = { title: string; paragraphs: string[] };
// Owner identity and retention/deletion targets are approved; deployment, legacy-data review, external-copy retention and final terms remain release gates.
// Never submit draft legal pages to Google or represent this flag as verification.
export const legalPublication = { approved: false, reviewedOn: "September 22, 2026", supportEmail: "cgarness.ffl@gmail.com" };
export const googleDataPolicyUrl = "https://developers.google.com/terms/api-services-user-data-policy";
export const googleConnectionsUrl = "https://myaccount.google.com/connections";
export const privacySections: LegalSection[] = [
  { title: "About this notice", paragraphs: ["AgentFlow is operated personally by Christopher Garness, who also goes by Chris Garness. AgentFlow is a CRM and communications application for life insurance agencies. This notice describes how the application handles account information, agency records and information from Google integrations.", "The retention and deletion targets below have been approved by the operator, but their implementation and backup handling must be verified before this draft is published. Your agency also determines how it uses the information in its workspace."] },
  { title: "Information used by AgentFlow", paragraphs: ["AgentFlow handles the account and profile information you provide, agency membership and permissions, and CRM records such as contacts, appointments and communications. Depending on the features you use, those communications can include email, text messages, call details and recordings.", "Technical information about requests, failures and activity helps operate and troubleshoot the service. Google credentials are used only by backend services to provide the integrations you authorize."] },
  { title: "Gmail access", paragraphs: ["When you connect Gmail, AgentFlow obtains your Google account identity and email address. It requests permission to read your mailbox and send messages you initiate in AgentFlow. Information imported can include sender and recipient addresses, subjects, message bodies, timestamps and conversation identifiers.", "The current import can include messages that have not been matched to a CRM contact. Connecting a personal mailbox can therefore bring personal messages into your agency workspace. Google authorization also permits background synchronization while you are signed out of AgentFlow.", "Initial synchronization retrieves a limited set of recent messages. That initial import window is not a retention period or a promise that your entire mailbox history will be imported."] },
  { title: "Google Calendar access", paragraphs: ["Calendar is an optional, separate integration. AgentFlow lists available calendars and accesses events to support your selected appointment synchronization settings. Depending on your sync mode, events can be read from Google Calendar or created and updated there from AgentFlow."] },
  { title: "Why Google information is used", paragraphs: ["Google information supports the email, contact history and appointment features you choose. It is not sold, used for advertising or used to train general-purpose AI models.", "AgentFlow follows the Google API Services User Data Policy, including its Limited Use requirements. Any new use of Google information must be reviewed and disclosed before it is enabled."] },
  { title: "Agency access and service providers", paragraphs: ["Imported communications are agency workspace records. Authorized users, including agency leadership where the applicable permissions allow it, may access those records. Connecting your mailbox does not give other agency users permission to use your Google credentials.", "AgentFlow uses Supabase for application data and backend processing and Vercel for hosting. Google processes requests to the connected Google services. Other enabled application features use providers such as Twilio for telephony and Resend for system email. The final provider and data-transfer disclosures must be verified before publication.", "Access by support personnel should be limited to the purposes permitted by Google's policies, such as a specific support request you authorize, investigating abuse or meeting applicable legal requirements."] },
  { title: "Storage and protection", paragraphs: ["Google connection credentials are restricted to backend services and protected separately from browser-visible connection details. Agency records use access controls intended to enforce the application's organization and role boundaries.", "No security certification or guarantee against every incident is represented by this notice."] },
  { title: "Disconnecting and removing Google access", paragraphs: ["Disconnecting an integration stops future synchronization by that integration and clears its saved credentials in AgentFlow. It does not automatically delete previously imported CRM history or necessarily remove Google's authorization.", "Use Remove Google access to stop AgentFlow's Google connections and request revocation. Because Google authorization can cover Gmail and Calendar together, this action can affect both. You can also remove AgentFlow from your Google Account's third-party connections. A request already in progress may finish before disconnect takes effect."] },
  { title: "Retention and deletion", paragraphs: ["Disconnecting Gmail stops future syncing. Previously imported emails remain in AgentFlow unless deleted separately. You can request deletion separately from disconnecting; disconnecting alone does not erase imported messages, activities, notifications or backups.", "The approved service target is to delete covered data within 30 calendar days after verifying a deletion request, sooner where required, and send confirmation afterward. The prepared Gmail process identifies one agency, user and source mailbox, includes attributable notification previews and email activities, and blocks deletion when older records cannot be reliably attributed. Deployment and operating procedures must be verified before this target is published as a service commitment.", "When an agent leaves an agency, the approved process is to remove their access and stop their Google integrations. Personal Google-data deletion requests are handled separately from the agency's shared client records.", "When an agency closes its workspace, the approved process provides a 30-day export window followed by deletion of its data, unless a specific retention obligation applies. An explicit deletion request does not have to wait through the export window.", "The approved backup target is for deleted data to expire from backups within 30 days after removal from the live system. Seven daily hosted database backups have been verified, and point-in-time recovery is not enabled. Storage objects, manual exports and other copies require separate review. A deletion ledger outside the database restore boundary and a verified restore procedure are required before this deadline is published as a service commitment.", "Deleting AgentFlow's local Gmail records does not delete messages from your Google mailbox. A later deliberate reconnect can import messages again. For questions about access or deletion of your information, contact the support address below and identify your agency and account. Do not send passwords, access tokens or unrelated mailbox content in a support request."] },
  { title: "Changes and contact", paragraphs: ["The published notice will identify its effective date and operator. Material changes to Google data use require updated disclosures and any consent required by Google's policies.", `Contact: ${legalPublication.supportEmail}`] },
];
export const termsSections: LegalSection[] = [
  { title: "Service and operator", paragraphs: ["AgentFlow is operated personally by Christopher Garness, who also goes by Chris Garness. AgentFlow provides software for agency CRM, communications and related workflows. These terms are a draft for owner review. Final commercial and legal terms must be confirmed before publication or acceptance by customers."] },
  { title: "Accounts and agency permissions", paragraphs: ["Use an account you are authorized to operate. Keep your sign-in credentials private and provide accurate account information. Agency administrators manage workspace membership and access according to the application's available permissions."] },
  { title: "Your records and communications", paragraphs: ["You are responsible for the records you upload and the communications you initiate, including having the permissions needed to use recipient information. Do not use AgentFlow for fraud, impersonation, unlawful communications, unauthorized access or distribution of malicious content.", "AgentFlow is software, not an insurer. Its availability does not establish that a communication, insurance transaction or agency practice satisfies every applicable requirement."] },
  { title: "Optional Google integrations", paragraphs: ["Connect only Google accounts you are authorized to use. Google determines which permissions you can grant and may restrict or revoke access. Your Google Workspace administrator may also impose restrictions.", "Gmail and Calendar behavior is described in the privacy notice and integration settings. You can disconnect an integration, remove Google access or request deletion of imported information through the published process."] },
  { title: "Third-party services and availability", paragraphs: ["Some features depend on services supplied by Google and other providers. Outages, revoked permissions or provider limits can interrupt those features. Do not assume a message was delivered or an appointment was synchronized unless the service reports the relevant result."] },
  { title: "Fees, cancellation and termination", paragraphs: ["Subscription, payment, cancellation, suspension and termination terms must be finalized with the operator before this draft is published. This draft does not create a new charge, refund promise or subscription commitment."] },
  { title: "Privacy and data handling", paragraphs: ["The privacy notice explains the intended data practices and Google integration controls. Imported records are not automatically deleted when you disconnect Google. The operator has approved the retention and deletion targets described in that notice; the corresponding process and backup handling must be implemented and verified before publication."] },
  { title: "Remaining legal terms", paragraphs: ["The operator must approve the final intellectual-property, warranty, liability, dispute-resolution and governing-law provisions before these terms are used as a customer agreement. This draft does not select a jurisdiction or require arbitration."] },
  { title: "Contact", paragraphs: [`Questions about AgentFlow: ${legalPublication.supportEmail}`] },
];
